apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  labels:
    app: kafka-schema-registry
spec:
  ports:
  - name: client
    port: 8081
    protocol: TCP
  selector:
    app: kafka-schema-registry