---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
      - name: kafka-schema-registry
        image: ghcr.io/arm64-compat/confluentinc/cp-schema-registry:7.1.1
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: kafka-cluster:9092
        - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
          value: PLAINTEXT
        #- name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
        #  value: zookeeper:2181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://localhost:8081
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: kafka-schema-registry

