apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    name: kafka-cluster
spec:
  ports:
  - name: client
    port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-cluster